package org.proteininformationresource.pirsr.uniprot.model;

/**
 * Author: Chuming Chen<br>
 * University of Delaware<br>
 * Center for Bioinformatics and Computational Biology<br>
 * Date: October 28, 2014<br>
 * <br>
 * 
 * The type of Comments on the entry.
 */
public enum EntryCommentType {

	ALLERGEN("ALLERGEN"),
	ALTERNATIVE_PRODUCTS("ALTERNATIVE_PRODUCTS"),
	BIOPHYSICOCHEMICAL_PROPERTIES("BIOPHYSICOCHEMICAL PROPERTIES"),
	BIOTECHNOLOGY("BIOTECHNOLOGY"),
	CATALYTIC_ACTIVITY("CATALYTIC_ACTIVITY"),
	CAUTION("CAUTION"),
	COFACTOR("COFACTOR"),
	DEVELOPMENTAL_STAGE("DEVELOPMENTAL_STAGE"),
	DISEASE("DISEASE"),
	DISRUPTION_PHENOTYPE("DISRUPTION_PHENOTYPE"),
	DOMAIN("DOMAIN"),
	ENZYME_REGULATION("ENZYME_REGULATION"),
	FUNCTION("FUNCTION"),
	INDUCTION("INDUCTION"),
	INTERACTION("INTERACTION"),
	MASS_SPECTROMETRY("MASS_SPECTROMETRY"),
	MISCELLANEOUS("MISCELLANEOUS"),
	PAGE("PAGE"),
	PATHWAY("PATHWAY"),
	PHARMACEUTICAL("PHARMACEUTICAL"),
	POLYMORPHISM("POLYMORPHISM"),
	PTM("PTM"),
	RNA_EDITING("RNA_EDITING"),
	SEQUENCE_CAUTION("SEQUENCE_CAUTION"),
	SIMILARITY("SIMILARITY"),
	SUBCELLULAR_LOCATION("SUBCELLULAR_LOCATION"),
	SUBUNIT("SUBUNIT"),
	TISSUE_SPECIFICITY("TISSUE_SPECIFICITY"),
	TOXIC_DOSE("TOXIC_DOSE"),
	UNKNOW("UNKNOWN"),
	WEB_RESOURCE("WEB_RESOURCE");
	
	private String value;
	
	EntryCommentType(String value) {
		this.value = value;
	}
	
	String getValue() {
		return this.value;
	}
}
