package org.proteininformationresource.pirsr.uniprot.model;

/**
 * Author: Chuming Chen<br>
 * University of Delaware<br>
 * Center for Bioinformatics and Computational Biology<br>
 * Date: October 28, 2014<br>
 * <br>
 * 
 * The type of Database cross references.
 */
public enum EntryDatabaseType {

	Allergome("Allergome"),
	ArachnoServer("ArachnoServer"),
	ArrayExpress("ArrayExpress"),
	BRENDA("BRENDA"),
	Bgee("Bgee"),
	BindingDB("BindingDB"),
	BioCyc("BioCyc"),
	BioGrid("BioGrid"),
	BioMuta("BioMuta"),
	CAZy("CAZy"),
	CCDS("CCDS"),
	CDD("CDD"),
	CGD("CGD"),
	COMPLUYEAST_2DPAGE("COMPLUYEAST-2DPAGE"),
	CTD("CTD"),
	CYGD("CYGD"),
	ChEMBL("ChEMBL"),
	ChiTaRS("ChiTaRS"),
	CleanEx("CleanEx"),
	ConoServer("ConoServer"),
	DEPOD("DEPOD"),
	DIP("DIP"),
	DMDM("DMDM"),
	DNASU("DNASU"),
	DOSAC_COBS_2DPAGE("DOSAC-COBS-2DPAGE"),
	DisProt("DisProt"),
	DrugBank("DrugBank"),
	EMBL("EMBL"),
	ESTHER("ESTHER"),
	EchoBASE("EchoBASE"),
	EcoGene("EcoGene"),
	Ensembl("Ensembl"),
	EnsemblBacteria("EnsemblBacteria"),
	EnsemblFungi("EnsemblFungi"),
	EnsemblMetazoa("EnsemblMetazoa"),
	EnsemblPlants("EnsemblPlants"),
	EnsemblProtists("EnsemblProtists"),
	EPD("EPD"),
	EuPathDB("EuPathDB"),
	ExpressionAtlas("ExpressionAtlas"),
	EvolutionaryTrace("EvolutionaryTrace"),
	FlyBase("FlyBase"),
	GO("GO"),
	Gene3D("Gene3D"),
	GeneCards("GeneCards"),
	GeneFarm("GeneFarm"),
	GeneID("GeneID"),
	GeneReviews("GeneReviews"),
	GeneTree("GeneTree"),
	Genevisible("Genevisible"),
	GeneWiki("GeneWiki"),
	Genevestigator("Genevestigator"),
	GenoList("GenoList"),
	GenomeRNAi("GenomeRNAi"),
	Gramene("Gramene"),
	GuidetoPHARMACOLOGY("GuidetoPHARMACOLOGY"),
	H_InvDB("H-InvDB"),
	HAMAP("HAMAP"),
	HGNC("HGNC"),
	HOGENOM("HOGENOM"),
	HOVERGEN("HOVERGEN"),
	HPA("HPA"),
	InParanoid("InParanoid"),
	IntAct("IntAct"),
	InterPro("InterPro"),
	KEGG("KEGG"),
	KO("KO"),
	LegioList("LegioList"),
	Leproma("Leproma"),
	MEROPS("MEROPS"),
	MGI("MGI"),
	MIM("MIM"),
	MINT("MINT"),
	MaizeGDB("MaizeGDB"),
	MalaCards("MalaCards"),
	MaxQB("MaxQB"),
	MoonProt("MoonProt"),
	NextBio("NextBio"),
	OGP("OGP"),
	OMA("OMA"),
	Orphanet("Orphanet"),
	OrthoDB("OrthoDB"),
	PANTHER("PANTHER"),
	PATRIC("PATRIC"),
	PDB("PDB"),
	PDBsum("PDBsum"),
	PIR("PIR"),
	PIRSF("PIRSF"),
	PMAP_CutDB("PMAP-CutDB"),
	PRIDE("PRIDE"),
	PRINTS("PRINTS"),
	PRO("PRO"),
	PROSITE("PROSITE"),
	PaxDb("PaxDb"),
	PeptideAtlas("PeptideAtlas"),
	PeroxiBase("PeroxiBase"),
	Pfam("Pfam"),
	PharmGKB("PharmGKB"),
	PhosSite("PhosSite"),
	PhosphoSite("PhosphoSite"),
	PhylomeDB("PhylomeDB"),
	PomBase("PomBase"),
	PptaseDB("PptaseDB"),
	ProDom("ProDom"),
	ProMEX("ProMEX"),
	ProteinModelPortal("ProteinModelPortal"),
	Proteomes("Proteomes"),
	PseudoCAP("PseudoCAP"),
	REBASE("REBASE"),
	REPRODUCTION_2DPAGE("REPRODUCTION-2DPAGE"),
	RGD("RGD"),
	Reactome("Reactome"),
	RefSeq("RefSeq"),
	SABIO_RK("SABIO-RK"),
	SGD("SGD"),
	SIGNOR("SIGNOR"),
	SMART("SMART"),
	SMR("SMR"),
	STRING("STRING"),
	SUPFAM("SUPFAM"),
	SWISS_2DPAGE("SWISS-2DPAGE"),
	SwissLipids("SwissLipids"),
	SwissPalm("SwissPalm"),
	SignaLink("SignaLink"),
	TAIR("TAIR"),
	TCDB("TCDB"),
	TIGRFAMs("TIGRFAMs"),
	TreeFam("TreeFam"),
	TopDownProteomics("TopDownProteomics"),
	TubercuList("TubercuList"),
	UCD_2DPAGE("UCD-2DPAGE"),
	UCSC("UCSC"),
	UniCarbKB("UniCarbKB"),
	UniGene("UniGene"),
	UniPathway("UniPathway"),
	VectorBase("VectorBase"),
	WBParaSite("WBParaSite"),
	World_2DPAGE("World-2DPAGE"),
	WormBase("WormBase"),	
	Xenbase("Xenbase"),
	ZFIN("ZFIN"),
	dictyBase("dictyBase"),
	eggNOG("eggNOG"),
	euHCVdb("euHCVdb"),
	mycoCLAP("mycoCLAP"),
	neXtProt("neXtProt"),
	GeneDB("GeneDB"),
	iPTMnet("iPTMnet"),
	CollecTF("CollecTF");
	
	private String value;
	
	EntryDatabaseType(String value) {
		this.value = value;
	}
	
	String getValue() {
		return this.value;
	}
}
