package edu.udel.bioinformatics.pirsr.propagation.annotation;

public enum AnnotationType {
	
	COMMENT_COFACTOR("COMMENT_COFACTOR"),
	COMMENT_PTM("COMMENT_PTM"),
	COMMENT_FUNCTION("COMMENT_FUNCTION"),
	COMMENT_SIMILARITY("COMMENT_SIMILARITY"),
	COMMENT_SUBCELLULAR_LOCATION("COMMENT_SUBCELLULAR_LOCATION"),
	COMMENT_SUBUNIT("COMMENT_SUBUNIT"),
	FEATURE_ACT_SITE("FEATURE_ACT_SITE"),
	FEATURE_BINDING("FEATURE_BINDING"),
	FEATURE_CROSSLNK("FEATURE_CROSSLNK"),
	FEATURE_DISULFID("FEATURE_DISULFID"),
	FEATURE_LIPID("FEATURE_LIPID"),
	FEATURE_METAL("FEATURE_METAL"),
	FEATURE_MOD_RES("FEATURE_MOD_RES"),
	FEATURE_MOTIF("FEATURE_MOTIF"),
	FEATURE_NP_BIND("FEATURE_NP_BIND"),
	FEATURE_REGION("FEATURE_REGION"),
	FEATURE_SITE("FEATURE_SITE"),
	FEATURE_ZN_FING("FEATURE_ZN_FING"),
	KEYWORD("KEYWORD");

	private String annotationType;
	
	AnnotationType(String annotationType) {
		this.annotationType = annotationType;
	}
	
	String getAnnotationType() {
		return this.annotationType;
	}

}
