//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.05.16 at 02:29:13 PM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ebi.ac.uk/interpro/resources/schemas/interproscan5", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.proteininformationresource.pirsr.interproscan5.model;
